linuxdeepin/dtkwidget

src/widgets/dapplication.cpp

不能按引用捕获lambda函数，匿名函数本身是一个指针，这种情况类似于：
````
void test() {
int *a = new int(1);
auto fun = [&a] {
qDebug() << *a;
};
}
````

fix: crash at DApplicationPrivate::cancelNotification

---

src/widgets/dabstractdialog.cpp
src/widgets/dabstractdialog.h

and the screens have different device pixel ratios
fix: https://github.com/linuxdeepin/internal-discussion/issues/1186

fix: The dialog size abnormally on multi-screen

---

debian/libdtkwidget2.symbols

修复在shuttle构建包时失败，提示找不到gtk gnome相关符号

fix: remove extra symbols

---

src/widgets/dtitlebar.cpp
src/widgets/dtitlebar.h

Notice that WindowSystemMenuHint not mean user menu, but mean Close
Button, Do not use it in DTitlebar. See blow link for more:
https://doc.qt.io/qt-5/qt.html#WindowType-enum
Change-Id: Ifad262ea190c1fb4778edfd0b525ef0c04e0e4ff

fix: always show menu button

---

src/widgets/dtitlebar.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1625
默认时只在普通类型窗口的标题栏上显示菜单按钮

fix: hide the non-window type window titlebar menu button on initialize

---

src/util/dwindowmanagerhelper.cpp
src/util/dwindowmanagerhelper.h
src/widgets/dabstractdialog.cpp
src/widgets/dplatformwindowhandle.cpp
src/widgets/dplatformwindowhandle.h

Support for custom window decorators using new interfaces
See: https://github.com/linuxdeepin/qt5dxcb-plugin/pull/25
支持调用窗管提供的隐藏标题栏接口来实现个性化定制窗口的功能

feat: add "enableNoTitlebarForWindow" for DPlatformWindowHandle

---

.release.json

Version number no longer depends on datetime
使用当前分支最新tag之后的commit数量当做版本号+r之后的值，不再依赖日期和时间

refactor: use commit count for the package version

---

src/widgets/dabstractdialog.cpp
src/widgets/dthememanager.cpp

If we don't require an UI update here, then `Qt::FramelessWindowHint` window will not able to apply custom QSS. The one from DTK will be used, the one from user can be set but doesn't works, so we need a polish() call here.
The problem comes after 9a9bf0b24d7c3beb458d64c23d750add3362b0d5 which removed the `Qt::FramelessWindowHint` window flag from DAbstractDialog, which also affacted the DSettingsDialog won't show the close button and option with buttongroup type correctly, and also linuxdeepin/developer-center#1378 since the preview dialog also use DAbstractDialog.
Minimum way to reproduce this issue is, create a `QApplication`(we don't need a `DApplication` to reproduce this issue), create a new class with `DAbstractDialog` as base class, apply a custom QSS on it.
``` cpp
// sample …
```

fix: update style after apply dtk stylesheet

---

rpm/dtkwidget.spec

Fedora no longer installs make in the default build environment.
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

fix: rpm BuildRequires make

---

src/widgets/dtitlebar.cpp

之前适配了wayland的关闭按钮的禁用功能，未考虑全面
Log: 
Influence: wayland 下所有 dtk 应用的关闭按钮的禁用状态
Bug: https://pms.uniontech.com/bug-view-117469.html

fix: wayland 下关闭按钮禁用后不能取消禁用状态

---

src/widgets/darrowrectangle.cpp

wayland 下绘制透明的区域没有鼠标穿透导致无法点击后面的控件。
如果 handle 无效，则使用 qwidget::setmask
Bug: https://pms.uniontech.com/bug-view-99340.html
Influence: wayland-DArrowRectangle-dde-calendar
Change-Id: I0ce66452e443acf88cd3b5b72514ed3bff3a8bd2

fix: wayland DArrowRectangle mouse propagation

---

src/widgets/dtextedit.cpp

修改DTextEdit的frame_radius为之前的1/2
Log: 修复通过控制中心修改字体，全英文文件名称编辑最后一行显示超长问题
Bug: https://pms.uniontech.com/bug-view-118769.html
Influence: 文本框字体显示

fix: 通过控制中心修改字体，全英文文件名称编辑最后一行显示超长

---

src/widgets/dkeysequenceedit.cpp

在非active状态下，将颜色（109，109，109）
做blendColor调整后的颜色设为背景色
Log: 非active状态下，快捷键背景色调整
Influence: 快捷键样式

chore: 非active快捷键背景色调整

---

src/widgets/dtextedit.cpp

when NoTextInteraction was set, createStandardContextMenu() return nullptr.
Log: DTextEdit崩溃问题修复
Influence: DTextEdit-menu-crash
Change-Id: I632d90555809bcb844fab7e1fbbccf3e816e8b3a

chore: DTextEdit crashed when NoTextInteraction was set

---

src/widgets/dalertcontrol.cpp

增加对UpdateRequest事件类型的判断
Log: 修复wayland下tooltips未跟随输入框问题
Bug: https://pms.uniontech.com/bug-view-124413.html
Influence: 输入框警告信息

fix: wayland下tooltips没有跟随输入框

---

src/widgets/dabstractdialog.cpp
src/widgets/dmainwindow.cpp
src/widgets/dtitlebar.cpp

适配了无标题栏后，旧版kwin上的无标题栏会显示两列按钮
不支持无标题栏时dtk的标题栏不应该显示菜单
Log:
Influence:

chore: wayland无标题栏兼容旧版kwin

---

src/widgets/darrowrectangle.cpp

网络连接对话框在设置了屏幕缩放的情况下会透过鼠标事件
导致点击不上按钮，原因是setMask之前要清空旧值
Log:
Bug: https://pms.uniontech.com/bug-view-130007.html
Influence: DarrowRectangle的点击操作

fix: wayland环境网络链接对话框点击无效

---

src/widgets/dprintpreviewdialog.cpp

主动设置了titlebar的palette后，要在主题变化的时候再次主动更新
Log:
Bug: https://pms.uniontech.com/bug-view-129709.html
Influence: 标题栏随主题色变化

fix: 打印预览titlebar不跟随主题变化

---

src/widgets/dtitlebar.cpp

fix: 废弃的接口更新

---

src/widgets/private/settings/content.cpp

设置backgroundGroup的useWidgetBackground为false
Log: 修复设置界面backgroundGroup背景色问题
Bug: https://pms.uniontech.com/bug-view-138331.html
Influence: 设置界面背景色

fix: 设置界面backgrounGroup背景色问题

---

src/widgets/dcrumbedit.cpp

双击时保存当前文本内容和当前背景色。
如果文本没有变化，则仍然使用当前背景色。
Log: 修复双击文件标记框后会随机变色问题
Bug: https://pms.uniontech.com/bug-view-139561.html
Influence: 标记框
Change-Id: Ic0315f06bb2ee55da94e8cf9e1bdfd8a649e7922

fix: 双击文件标记框后会随机变色

---

src/widgets/dstyleditemdelegate.cpp

1.判断listview窗体是否激活，设置其状态。
2.设置非激活状态下的colorgroup为QPalette::Inactive。
Log: 修复非激活listview内字体样式未置灰问题
Bug: https://pms.uniontech.com/bug-view-138395.html
Influence: listview非激活状态UI

fix: 非激活listview内的字体样式未置灰

---

src/widgets/dlineedit.cpp

showAlertMessasge(const QString&, int)的follower是dlineedit，
但是, dlinedit的布局里面是qlineedit，
所以在eventFilter里,检查follower的visibleRegion是空的，
修改follower为qlineedit。
Log: 修复dspinbox的showAlertMessage接口不起作用
Task: https://pms.uniontech.com/task-view-152843.html
Influence: dspinbox,lineedit警告信息
Change-Id: Ibc026ee110ee1e93e50f3788b923802488490110

fix: dspinbox的showAlertMessage(const QString&,int)接口不能显示警告信息

---

src/widgets/darrowrectangle.cpp

darrowrectangle在updateClipPath时设置属性clipPath，
并且传递参数polygon
Log: 修复锁屏界面网络面板显示异常，底色有重叠黑影问题
Bug: https://pms.uniontech.com/bug-view-124427.html
Influence: wayland下darrowrectangle的UI
Change-Id: Ie398c651c743dae514ce86ee29e88c7de1c9645b

fix: 锁屏界面网络面板显示异常，底色有重叠黑影

---

src/widgets/dprintpreviewdialog.cpp

use QPageSize::name() instead of QPageSize::key()
a localized human-readable name for the page size.
Log:
Influence: printpreview pagesize
Change-Id: I897ef3cc35668a87aa744dbe54f3ae3849bc2206

fix: change pagesize name to readable name

---

src/widgets/dcrumbedit.cpp

当光标在内容末尾且鼠标双击位置在光标右边时，
编辑返回false，不再编辑追加文字。
Log: 修复双击标记框内标记后面追加文字问题
Bug: https://pms.uniontech.com/bug-view-139561.html
Influence: 标记框
Change-Id: Ia582ebf7f40b8180352bfdfec09ac5f615047212

fix: 双击标记框内标记后面追加文字

---

src/widgets/dwaterprogress.cpp

The default value is 0. In setValue function, the text content will not be updated because the value is equal.
Issue: https://github.com/linuxdeepin/developer-center/issues/3292
Log: 修复 DWaterProgress 进度初始化为 0 时文字不显示
依赖 https://github.com/linuxdeepin/dtkcommon/pull/13

fix: DWaterProgress not displayed text when initialized to 0

---

examples/dwidget-examples/collections/listviewexample.cpp
src/widgets/dstyleditemdelegate.cpp
src/widgets/dstyleditemdelegate.h
tests/testcases/widgets/ut_dstyleditemdelegate.cpp

DStandardItem's `setActionList` can't be used with drag because of
Type doesn't support metatype's save and load.
and DStandardItem doesn't release it's Action when destruction,
we use sharedpointer to manager action's life.
Add clone override function to support that action can be access
after draged, and it need to setItemPrototype by model.
Log: 含有Action项的DListView拖动时程序崩溃
Change-Id: Idc489b94f4cf95850fe00a9ac8231fed80913a79

fix: crashed when DListView drag item with Action

---

src/widgets/dlineedit.cpp
src/widgets/dtextedit.cpp

语音助手在某些情况下会不响应，这是直接构造 QDBusInterface
会卡死，加一个 Ping 的操作，如果 300ms 内未响应则不添加
相关菜单
Bug: https://pms.uniontech.com/bug-view-151279.html
Log:
Influence: edit context menu
Change-Id: Id8e3f6f53a011b70fa12d95ff1cc3a6fec94021b

fix: 调用语音助手服务不响应导致右键菜单卡死

---

src/widgets/dstyleditemdelegate.cpp
src/widgets/dstyleditemdelegate.h

1. Add an interface to set the DCI icon in DListView.
2. Add drawing support for DCI icon in DStyledItemtDelegate.
Log:
Influence: None
Change-Id: If4ed076e8c2a819b28e5d046f885a22b6c0b8272

feat: Enable DListView and DViewItemAction to support DciIcon

---

src/widgets/darrowrectangle.cpp

wayland 下没有创建 handle，导致没有创建 blureffectwidget
需要有这个才可以让模糊的窗口在黑色背景下看清黑色的文字
增加判断只在 dwayalnd 下加上设置模糊的路径，不影响xcb逻辑
Log: 修复 wayland下 darrowrectangle 文字看不清的问题
Bug: https://pms.uniontech.com/bug-view-148535.html
Influence: wayland networkdialog
Change-Id: I9ca12630e30cca02503efa3f177f3626da749a6a

fix: setBackgroundColor not work on wayland

---

src/widgets/dlineedit.cpp
src/widgets/dtextedit.cpp

when calling the dbus in BlockWithGui mode , the event will
be passed to the edit, causing the edit to gain focus, and
the edit will lose focus when the menu pops up.
so Let the bullets fly
Bug: https://pms.uniontech.com/bug-view-154857.html
Log:
Inlfluence: DSearchEdit-ContextMenu-Focus
Change-Id: Ic2ee354e78dd2f2382da3d8c7877926f465d1946

fix: Edit focus blinks on right click

---

src/widgets/dstyleditemdelegate.cpp

miss to cast for QList<DViewItemAction*>,
only cast DViewItemActionList, it causes sizeHint calculates error.
Log: DListView的sizeHint计算错误导致各项堆叠
Bug:  https://pms.uniontech.com/bug-view-155683.html
Influence: 用到了DListView，并且使用到了DViewItemAction的所有应用
Change-Id: I13506bcfed970c9733a50130c92e421e71457805

fix: DListView's size calculates error

---

src/widgets/dstyleditemdelegate.cpp
src/widgets/dstyleditemdelegate.h

Add clone() override, it can't find DStandardItem::clone symbol
in some scene,
for example, class A inherited DStandardItem, it compiled in
environment that has the symbol, and it run in not has symbol
environment.
we can't use textActionList() and actionList() to get data
when draged with Action Item, because create a new QStandardItem
instead of DStandardItem, we should record the origin data ourselves.
we can't use DVtableHook::overrideVfptrFun, we don't have
right time to override clone() function, because we don't implement
constructor.
Log: 添加重写的虚函数clone导致接口不兼容
Influence: 文管应用在高版本的dtkwidget下打包，低版本的dtkwidget下无法启动
Change-Id: I38da9ec4694a3c67510415989e516f5f977d4bf7

fix: incompatible because of added clone function

---

tests/testcases/widgets/ut_dstyleditemdelegate.cpp

we remove DStandardItem::clone due to incompatible in V23,
item->clone() call QStandardItem's function actually, so it
isn't a DStandardItem, but the clone's intention need to be test.
it doesn't need to cherry-pick to master.
Log: 单元测试失败
Bug: https://pms.uniontech.com/bug-view-156901.html
Influence: 无
Change-Id: Ibac6bc721104bb0bc2f16c3a63a12fbc20e88f22

fix: UT error

---

tests/test-recoverage.sh

A mistake, since the target name changed, the target name in shell
should also change
Log: fix recoveryshell

fix(shell): wrong target

---

src/widgets/dstyle.cpp

Add Anitialiasing flag when drawing FloatingButton's panel.
Log: 在绘制FloatingButton面板时添加抗锯齿属性
Bug: https://pms.uniontech.com/bug-view-153687.html 
Influence: 所有使用了FloatingButton和CE_FloatingWidget的应用， 都会减少阴影部分的锯齿
Change-Id: Iabca0e0b3f6b1d14e245e8386733dcb48b7e83c3

fix: FloatingButton Antialiasing doesn't obvious

---

plugin/dtkuiplugin/CMakeLists.txt

log: 删除无用的 DtkWidget_INCLUDE_DIRS

fix: remove useless variable

---

src/widgets/dprintpreviewdialog.cpp

非自定义时，隐藏输入框;
自定义时，显示输入框。
Log: 修复自定义水印文字问题
Bug: https://pms.uniontech.com/bug-view-158803.html
Influence: 自定义水印输入框
Change-Id: Ibff01f401db9c93e773fe8f16755554a1256f547

fix: 自定义水印文字问题

---

src/widgets/dprintpreviewdialog.cpp

设置打印预览页边距UI的间距为10px
Log: 修复页面设置间距不对的问题
Bug: https://pms.uniontech.com/bug-view-158805.html
Influence: 打印预览页边距UI
Change-Id: I3553112e875a924cd1b322384c04a722ec48727b

fix: 打印预览页面设置间距不对

---

src/widgets/dprintpreviewdialog.cpp

初始化时setAlert为false
Log: 修复error状态一开始就默认出现问题
Bug: https://pms.uniontech.com/bug-view-158801.html
Influence: 打印预览页面范围输入状态
Change-Id: I47e5e5c0f8a8b082e973eb671dcab8208ca2e677

fix: error状态一开始就默认出现

---

src/CMakeLists.txt

原来使用 qmake 时，生成的 qm 文件在 src/translations 下
切换分支后，使用 src/translations/* 会重复生成相同的 qm 文件，
需要主动删除一下qm文件才可以(如 git clean -dfx)，否则报错
CMake Error at Qt5LinguistToolsMacros.cmake:105 (add_custom_command): Attempt to add a custom rule to output which already has a custom rule.
Log: none
Influence: cmake build
Change-Id: I089403b4f0406baa4f97e1270f5d092256f97fb2

chore: 使用 *.ts 添加翻译文件

---

src/widgets/darrowrectangle.cpp

setBackgroundColor里面增加个isFloatWindow的判断
Log: 修复wayland下分屏窗口在暗主题上异常问题
Influence: 分屏窗口UI
Change-Id: Icc2819bc2d3033b6233ce523336daa236683e003

chore: wayland下分屏窗口在暗主题上异常

---

src/widgets/dprintpreviewdialog.cpp

原因：DBackgroundGroup的layout未设置margin为0，
DBackgroundGroup的默认itemMargin为9，
影响其圆角大小。
修改：设置DBackgroundGroup的layout的margin为0，在其子widget里设置margin。
Log: 修复打印预览水印项的圆角和其他项的不一致问题
Bug: https://pms.uniontech.com/bug-view-158803.html
Influence: 打印预览水印项UI
Change-Id: I88497151148d1f2c9e19e3192661275528bb5be0

fix: 打印预览水印项的圆角和其他项的不一致

---

src/widgets/dprintpreviewdialog.cpp

当页面范围是All或Current Page, 隐藏输入框；
当页面范围是Select Pages, 显示输入框。
Log:
Influence: 打印预览-页面范围输入框
Change-Id: Ic33c920a7f279ddeaf3d6703a42918892b706f12

chore: 打印预览页面范围输入框调整

---

src/widgets/dstyle.cpp

QCommandLinkButton在qt源码中进行了一次pixmap变换，这导致前端拿不到位图
这里将QCommandLinkButton 的icon直接返回了QIcon theme,避免了pixmap的变换
Log: qcommandlinkbutton 的高分屏模糊bug
Influence: qcommandlinkbutton

fix: qcommandlinkbutton 主题

---

include/dtkwidget/widgets/dprintpreviewsettinginterface.h
src/widgets/dprintpreviewdialog.cpp

原因：根据对象名字关闭控件，开关和下面功能控件一个对象名。
解决：增加一个对象名字控制下面的功能控件。
Log: 修复打印预览页面打开“添加水印”开关后再关闭，水印开关消失问题
Bug: https://pms.uniontech.com/bug-view-163737.html
Influence: 水印
Change-Id: I5b0f10347b668987cadf7b2542fbea8ea8b8b437

fix: 打印预览页面打开“添加水印”开关后再关闭，水印开关消失

---

src/widgets/dsearchedit.cpp

搜索框文字偏左12px
Log: 修复搜索框文字没有居中问题
Bug: https://pms.uniontech.com/bug-view-167567.html
Influence: 搜索框
Change-Id: I8ca4b6eb019da4fbe93ddcb7a612242c6403cd77

fix: 搜索框文字没有居中

---

src/widgets/dapplication.cpp
src/widgets/private/dapplication_p.h

moving implement of loadTranslator to dtkgui.
Log: 加载翻译功能移至dtkgui，以便供dtkdeclarative使用
Bug: https://pms.uniontech.com/bug-view-157977.html
Influence: qml相关应用没有加载翻译
Change-Id: Ic31ea60854c0685add5617f795aea061e8a20e3b

feat: Using loadTranslator of dtkgui

---

src/widgets/dprintpreviewdialog.cpp

1.修改label的水平宽度的策略为QSizePolicy::Maximum
2.布局中间加个弹簧
Log: 修复维语环境下打印设置界面标题没有对整齐问题
Bug: https://pms.uniontech.com/bug-view-163971.html
Influence: 打印设置-维语
Change-Id: I48bbe47544112267a1e8f8284db508af05f5e48f

fix: 维语环境下打印设置界面标题没有对整齐

---

src/widgets/dtitlebar.cpp

old dtkwidget assume menu is not empty, but now it's not, and
we revert this code.
Moving addDefaultMenuItems from `showMenu` to `showEvent`,
because some applications get menuItems and assert they are not empty before  `showMenu`.
delay to check UserManual avoid to request dbus in `showEvent`.
Log: 升级后DTitleBar提供的menu可能没有默认菜单项，导致部分应用异常，改回
原来版本的逻辑
Bug: https://pms.uniontech.com/bug-view-170639.html Influence: 升级dtkwidget导致包管理器使用安装功能时崩溃
Change-Id: Ifae616c8ba5af3a2e28b1dbb00009e0a2872a989

fix: DTitleBar exists incompatible modify

---

src/widgets/dstyle.cpp

QCommandLinkButton在qt源码中进行了一次pixmap变换，这导致前端拿不到位图
这里将QCommandLinkButton 的icon直接返回了QIcon theme,避免了pixmap的变换
Log: qcommandlinkbutton 的高分屏模糊bug
Influence: qcommandlinkbutton
Change-Id: Ibf6c35394373abed5913fb66729c6bf4fcce466f

fix: fix: qcommandlinkbutton缩放后图标模糊

---

src/widgets/dstyleditemdelegate.cpp

QStyledItemDelagate::eventFilter can filter the object's Tab
key event, here We only need a Paint Event to post UpdateWidgetVisibleEvent, and updateWidgetVisible, so we remove the eventFilter of AbstractItemView
Log: DStyleItemDelegate拦截了QListView的部分事件，导致listview的Tab 事件和焦点异常
Bug: https://pms.uniontech.com/bug-view-164547.html 
Influence: 使用了DListView的应用，其listview的tab键，焦点事件可能
异常，
Change-Id: I1d4d8c836b5c6b27e021a5d632b969daf3f5b348

fix: DStyleItemDelegate filter ListView's event

---

src/widgets/dprintpreviewdialog.cpp

原因：匹配的是key字段，实际combobox内容是name字段
修改: 将匹配的key字段修改成name字段
Log: 修复打印文件设置纸张大小不生效
Bug: https://pms.uniontech.com/bug-view-171767.html
Influence: 打印纸张大小
Change-Id: I557072ca5592059031a71c4bbb4bb8e1ecabe154

fix: 打印文件设置纸张大小不生效

---

CMakeLists.txt

Removing asan check
Log: 移除库的asan检测
Change-Id: If37bca2925c43ff87701fe58f1136dab66cce2a8

fix: Remove ASan check for debug

---

misc/DtkWidgetConfig.cmake.in

Fix DtkWidget_LIBRARIES to find_library installed.
Log: fix linking error

chore: fix linking error

---

src/widgets/dcrumbedit.cpp

Some crumbs will get out of panel frame border of DCrumbEdit when it's too long or there are too many crumbs showing in a vertical line (often happens when scrolling).
Draw border first and then draw viewport, set viewport margins.
Bug: https://pms.uniontech.com/bug-view-174437.html
Log: fix crumbs out of border
Influence: DCrumbEdit

fix: crumbs get out of border in DCrumbEdit

---

src/widgets/dtabbar.cpp

map position from Native will scale with deviceRatio
Bug: https://pms.uniontech.com/bug-view-70386.html
Log: none
Influence: drag tabbar with high dpi

fix: hotSpot pos not scaled

---

include/dtkwidget/widgets/dstyle.h

Modify default value for m_style of DStyleHelper from nullptr to QApplication::style in case we have a stack overflow.
Log: correct default constructor for DStyleHelper

fix: correct default constructor for DStyleHelper

---

src/widgets/dtitlebar.cpp

新建dtitlebar对象，未调用settings()，titlebarSettingsImpl是空的
Log: 增加titlebarSettingsImpl空指针判断
Influence: dtitlebar
Change-Id: I6f330f59556b86b34e94c8cb8997556c7bb59e8e

fix: 增加titlebarSettingsImpl空指针判断

---

src/widgets/dapplication.cpp
src/widgets/dfeaturedisplaydialog.cpp
src/widgets/dmainwindow.cpp

原因：特性对话框的父窗口是关于对话框时，
随着关于对话框销毁，再次访问特性对话框对象就会崩溃。
修改：1.特性对话框不设置父窗口，随着应用退出销毁。
2.特性对话框展示时，调整位置。
Log: 修复二次调起特性对话框崩溃问题
Influence: 特性对话框
Change-Id: I56671745ae6fb087133c34fcd50f54d4b9789e81

fix: 二次调起特性对话框崩溃

---

include/widgets/dfeaturedisplaydialog.h
src/widgets/daboutdialog.cpp
src/widgets/dfeaturedisplaydialog.cpp

the entrance of feature display is visible when no item is added
when no feature item is added, hide the entrance in about daboutdialog
Log: fix the issue about feature dialog has no content
Influence: feature display
Change-Id: Id13ce0b84ede3d084f219cfbd35e1d2a94e3b4bc

fix: the entrance of feature display is visible when no item is added

---

src/widgets/dfloatingbutton.cpp
src/widgets/dstyle.cpp

It was introduced in e4fdfe5b3683f0d68110b94dc98521de691f941f .
It cause incompatible that DStyleOptionButton add a member
variable `dciIcon`.
App is crashed if libdtkwidget5 is different between App built
and running loaded, (app builds with 5.5, but loads 5.6 version).
We shouldn't add member variable that defined in .h and which
breaks abi.
If this case has exist, we can Use DApplication::builtDtkVersion()
to avoid to accessing the member in some lower version.
We are lucky, because we have `features` to avoid to accessing
`dciIcon` member in lower version.
FloatingButton doesn't need add DciIcon to features, because
DDciIcon has execute this code.
Log: none
Influence: App crash in some case
Change-Id: Iff4d596c6f90fa82f0d93ec9db0118d8d0bffa40

fix: DStyleOptionButton's incompatible

---

src/widgets/dmainwindow.cpp
src/widgets/dtitlebar.cpp
src/widgets/private/dmainwindow_p.h

change background widget's visibility when the signal of expandChanged is emitted
Log: resolve the issue that background widget is always shown when sidebar is hidden
Influence: sidebar
Change-Id: I0a2fc73614aecfb736f52f00cb6ca07459f48fb7

fix: background widget is always shown when sidebar is hidden

---

include/widgets/dmainwindow.h
src/widgets/dmainwindow.cpp

obsolete old interface sidebarVisible due to spelling mistake
Log: rename sidebarVisble to sidebarVisible
Influence: sidebar
Change-Id: I7c932f4fc8f43db2271d3562d446b4f663e11ad4

chore: rename sidebarVisble to sidebarVisible

---

misc/DtkWidgetConfig.cmake.in

Older version CMake find_dependency has a defeat that COMPONENTS find will fail. Find single dependency separately to avoid this issue.
Log: fix find_dependency error

fix: find_dependency error

---

examples/collections/mainwindow.cpp

Hide the custom toolbar section in the example
Log: none

chore: hide custom toolbar in the example

---

src/widgets/dprintpreviewdialog.cpp

give the explicit result code (accept or reject) when pressing print button or cancel button of dprintpreviewdialog.
Log: modify the result code of dprintpreviewdialog to accept or reject
Influence: dprintpreviewdialog
Change-Id: Ic6ee36b7fc805ed16762bc203001d1248211fb1e

chore: modify the result code of dprintpreviewdialog to accept or reject

---

docs/widgets/dprintpreviewdialog.zh_CN.dox
include/widgets/dprintpreviewdialog.h
src/widgets/dprintpreviewdialog.cpp
src/widgets/private/dprintpreviewdialog_p.h
tests/testcases/printpreview/ut_dprintpreviewdialog.cpp

Add interface updateDialogSettingInfo, apps can update print dialog
settings at construction time.
Add docs and UT, fix a bug that may cause a memory leak.
Log: DPrintPreviewDialog add update setting interface.
Influence: Add update setting interface.

chore: DPrintPreviewDialog add update setting interface.

---

src/widgets/dprintpreviewdialog.cpp

add support for color-only mode to dprintpreviewdialog
Log: add color-only mode in dprintpreviewdialog
Issue: https://github.com/linuxdeepin/dtkwidget/issues/354
Influence: print preview

fix: add color-only mode in dprintpreviewdialog

---

src/widgets/dabstractdialog.cpp

if windowmanager not support blur window effect
do not set `Qt::WA_TranslucentBackground` attribute setblurEnabled will not work
Issue: https://github.com/linuxdeepin/dtkwidget/issues/358
Log: fix Dialog translucent background

fix: DAbstractDialog translucent background

---

examples/collections/windowexample.cpp

Clipping TitleBar control and modifing radius from 16 to DMainWindow's radius.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/323

fix: Modify style for example's titlebar

---

src/widgets/dstyle.cpp

Use `ButtonMargin` as Arrow's margin with frame, and changes it
from 8 to 10.
Modify Indicator in CompactMode.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/326

fix: Modify PushButton to adapt CompactMode

---

src/widgets/dstyle.cpp

SwitchButtonhandlerWidth is different,
It's SwitchButtonGroove's width is 40 in CompactMode, and 50 in NormalMode,
It's just by 5 / 3 * PM_SwitchButtonHandleWidth.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/326

fix: Adjust SwitchButtonhandler's width in CompactMode

---

examples/collections/listviewexample.cpp
src/widgets/dstyle.cpp
src/widgets/dstyleditemdelegate.cpp

In compact mode:
modify margins to margin(10, 6, 10, 6)
modify icon size to QSize(24, 24)
Log: modify listview in compact mode
Issue: https://github.com/linuxdeepin/dtkwidget/issues/324
Influence: compact mode

fix: modify listview for compact mode

---

src/widgets/dtitlebar.cpp

修改updateTitlebarHeight函数，取消titlebarHeight等于50的判断，配置文件默认值为-1
Issue: https://github.com/linuxdeepin/dtkwidget/issues/367

fix: update  updateTitlebarHeight

---

src/widgets/dsearchedit.cpp
src/widgets/dstyle.cpp

`search_indicator` and `search_action`'s size is 36 * 36, and
they have more than white space, now we update those icon in dtkgui and qt5integration, and remove unnecessary avoidance.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/325
Log: It depends dtkgui and qt5integration.

fix: Modify SearchEdit's icon

---

src/widgets/dstyle.cpp

set the handle's width to half of switchbutton's width; set the handle's height to switchbutton's height.
Log: modify the handle's size in switchbutton
Issue: https://github.com/linuxdeepin/dtkwidget/issues/389

fix: SwitchButtonHandle isn't expanded when switchbutton is expanded

---

src/widgets/dstyle.cpp

PM_LineEditIconSize is introduced in qt6.2 or patch,
the iconSize is always 20 in NormalMode or CompactMode. Building error is introduced in 'ec55b744d6ae766911d01948c56eac8b18fc5289'
Log:

fix: Build error for Qt 5.15~6.1

---

include/widgets/dstyle.h
src/widgets/dstyle.cpp

ButtonIconSize does't multiply ratio in dstyle, which lead to
both pixmap size and rect size disagree.
Log: modify ButtonIconSize's default value
Issue: https://github.com/linuxdeepin/dtkwidget/issues/390

fix: icon size is abnormal when dpi > 1

---

src/widgets/dstyleditemdelegate.cpp

It's apperent when we set a widget for DStandardItem, and
hovering it, it look obvious when changing Widget's cursor.
We hide widget depending on the different of last and current
frame, When we hover one item, Viewport also to be repaint, and it's area is an item hovered, this caused we made a calculation error.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/364

fix: ListView's widget switching hide and show frequently

---

src/widgets/dtoolbutton.cpp

set a fixed layout mode Qt::ToolButtonTextBesideIcon in codebase
Log: delete fixed layout Qt::ToolButtonTextBesideIcon
Issue: https://github.com/linuxdeepin/dtkwidget/issues/403

Fix: Qt::ToolButtonTextUnderIcon does't work

---

src/widgets/dstyle.cpp

According to designer.
It results display error for dde-control-center's shutcut keys
for `10`, so we change it back.
Issue: https://github.com/linuxdeepin/dtkwidget/pull/373

fix: Modify ButtonMargin from 10 to 8

---

src/widgets/dfloatingbutton.cpp
src/widgets/diconbutton.cpp

Option's `features` is overridden.

fix: DFloatingButton can't display dciicon

---

archlinux/PKGBUILD

It's not mentioned anymore in this project.

fix: remove unused librsvg dependency from PKGBUILD

---

archlinux/PKGBUILD

Fixes the following warning:
```
CMake Warning:
No source or binary directory provided.  Both will be assumed to be the
same as the current working directory, but note that this warning will
become a fatal error in future CMake releases.
```

fix: suppress cmake warning for missing directory specified

---

src/widgets/darrowrectangle.cpp

当给ArrowRectanble设置parent的时候，调用show方法没有计算顶层窗口的位置导致最终计算的窗口错误
Log: 修复锁屏界面竖屏无法显示网络列表
Influence: 登陆界面和锁屏界面的网络列表
Bug: https://pms.uniontech.com/bug-view-195913.html

fix: 修复ArrowRectanble设置位置错误

---

src/widgets/dmainwindow.cpp
src/widgets/dtitlebar.cpp

修复titlebarHeight属性被修改时，标题栏没有实时生效。
Issue: https://github.com/linuxdeepin/dtk/issues/51

fix: titlebar was not updated when titlebarHeight was changed

---

CMakeLists.txt

Log:
Never modify the value of CMAKE_INSTALL_PREFIX after including GNUInstallDirs ，Otherwise incorrect CMAKE_INSTALL_FULL_XXXX values will be computed

fix: must set CMAKE_INSTALL_PREFIX before GNUInstallDirs

---

include/widgets/dstyle.h
src/widgets/dstyle.cpp

In compact mode, add the margins to sizehint.
Log: modify floatbutton's content size to 36*36
Issue: https://github.com/linuxdeepin/dtk/issues/36

fix: adjust floatbutton's size in compact mode

---

src/util/ddesktopservices_linux.cpp

Use the activatableServiceNames instead of isServiceRegistered to detect new version dbus interfaces exists

chore: use activatableServiceNames

---

src/widgets/darrowrectangle.cpp

只Qt::Widget的窗口并有父窗口的计算使用父窗口rect
Log: 修改分屏菜单位置错误
Bug: https://pms.uniontech.com/bug-view-199083.html
Influence: 锁屏界面/任务栏等网络插件窗口显示,窗口分屏提示窗口

fix: 修改分屏菜单位置错误

---

src/widgets/dcrumbedit.cpp

QRandomGenerator::global() no need to call seed

fix: Attempted to overwrite a QRandomGenerator to system() or global().

---

src/widgets/dtitlebar.cpp

Titlebar has a targetWindow and it will sync disableFlags with window's motif functions. Do not set disableFlags according to the current state of buttons. Because when targetWindow(That is also top level window of titlebar) is disabled, all its children will always return false when invoking isEnabled.
Also, never explicitly disable any button unless you know when to enable it again. Let top level window manages it. DisableFlags only apply to configuration, will not reveal buttons' state.
Log: fix titlebar buttons don't recover

fix: titlebar buttons don't recover

---

src/widgets/dstyle.cpp

Adjust color's lightness by ColorType.
Issue: https://github.com/linuxdeepin/dtk/issues/82

fix: Button background lightness display error

---

docs/widgets/dbuttonbox.zh_CN.dox
src/widgets/dbuttonbox.cpp

doc: update docs for dbuttonbox

---

include/util/dhidpihelper.h
src/util/dhidpihelper.cpp
src/widgets/dsimplelistview.cpp
src/widgets/dtoast.cpp

DHiDPIHelper has nothing to do with dtkwidget. Move the only function loadNxPixmap to Dtk::Gui::DIcon. Deprecate the implementation in dtkwidget.
Log: deprecate dhidpihelper

chore: deprecate dhidpihelper

---

docs/widgets/dcrumbedit.zh_CN.dox
src/widgets/dcrumbedit.cpp

doc: update docs for dcrumbedit

---

src/widgets/dapplication.cpp

- dependcy: https://github.com/linuxdeepin/dtkgui/pull/183
- load qt and app translation files in dtkgui
- dtkwidget only load dtkwidget_xx.qm

chore: move loadtranslator to dtkgui

---

include/widgets/dstyleoption.h
src/widgets/dstyleoption.cpp
tests/testcases/widgets/ut_dstyleoption.cpp

- add T11 (default 8 px)
- T5 17px ==> 16px
Issue: https://github.com/linuxdeepin/dtk/issues/116

feat: DFontSizeManager tweak

---

src/widgets/dalertcontrol.cpp

show an empty alert frame makes no sense

chore: do not show alert message if text is empty 

---

src/widgets/dprintpreviewdialog.cpp

The current ColorMode is inconsistent with the set currentIndex after switch the printer.
Refresh the current print ColorMode after reset
the ColorMode combobox.
Log: ColorMode may be inconsistent with settings.
Bug: https://pms.uniontech.com/bug-view-219201.html
Influence: PrintPreview

fix: ColorMode may be inconsistent with settings.

---

src/widgets/dprintpreviewdialog.cpp

颜色选项默认选择第一项，第一项有可能是彩色或黑白，QCombobox在设置与之前相同的项的时候其CurrentIndexChanged信号不会被触发，正因如此，导致预览图没有及时没刷新，修改为在为组合框添加item的时候，将其currentIndex设置为-1，保证后续的CurrentIndexChanged信号及时被触发
Log: 修复打印预览，切换打印机的时候预览图颜色显示异常
Bug: https://pms.uniontech.com/bug-view-220315.html
Influence: 打印预览切换打印机时预览图的颜色表现

fix: 修复打印预览，切换打印机的时候预览图颜色显示异常

---

debian/rules

Because the store strictly limits the installation path of third-party applications. Adding this path may simplify third-party application development.

DTK_STATIC_TRANSLATION is set by default.

---

include/widgets/dstyle.h
src/widgets/dstyle.cpp

SH_UnderlineShortcut
Whether shortcuts are underlined.
SH_Menu_KeyboardSearch
Whether disable the typing to search for menu items

feat: styleHint tweak

---

src/widgets/dtabbar.cpp

Function verticalTabs is exposed by qtabbar_p.h as constexpr static
inline, original definition in dtabbar.cpp will lead to an redefinition
error. Just rename dtk's implementation.
Note: Probably we should replace private implementaion with Qt's
implementation after all versions of Qt expose this function.
Log: fix redefinition of verticalTabs

fix: redefinition of verticalTabs

---

src/widgets/darrowrectangle.cpp

radiusArrowStyleEnable 后 border 少了一些绘制路径
Issue: https://github.com/linuxdeepin/dtk/issues/92

fix: DArrowRectangle left/right style incorrect

---

src/widgets/private/startupnotifications/startupnotificationmonitor.cpp

Log:DApplication应用初始化时通过设置xcb窗口属性，设置了XCB_EVENT_MASK_PROPERTY_CHANGE事件掩码，此时Xorg会对发送给客户端的事件根据事件掩码来过滤，例如关闭文件选择对话框时发送的类型为focusIn的clientMessageEvent就不会发送给客户端。虽然在关闭对话框时，XOrg也会发送一次FocusIn底层事件，但这个事件和窗口的关闭信号有时序上的问题，所以真正重要的是前面所说的clientMessageEvent。故添加事件掩码以获取对应事件。
Bug: https://pms.uniontech.com/bug-view-220369.html

fix: DApplication初始化过程中会覆盖原有事件掩码，导致丢失事件

---

src/widgets/dcrumbedit.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6780

fix: double click edit incorrect format

---

include/widgets/danchors.h
include/widgets/darrowbutton.h
include/widgets/darrowrectangle.h
include/widgets/dloadingindicator.h
src/widgets/darrowrectangle.cpp

chore: remove unused headers in header

---

src/widgets/dslider.cpp

内容过长时，取省略号替代
Log:
Task: https://pms.uniontech.com/task-view-325247.html 
Influence: DSlider刻度标签显示
Change-Id: I47993df919b5fcc238db42b609b6183d5011e14a (cherry picked from commit 0b89d4cbcc9817b7829dfc5d196284f5c8de9945)

fix: 修复dslider刻度标签内容过长时，显示不下的问题

---

src/widgets/dlineedit.cpp
src/widgets/dpasswordedit.cpp
src/widgets/private/dlineedit_p.h

set the size of black circle to 6 pixel by changing the font,
set the letter spacing to 200 under PercentageSpacing type.
Issue: https://github.com/linuxdeepin/developer-center/issues/7335

fix: black circle in PasswordEdit

---

src/widgets/dalertcontrol.cpp

Don't hide alert message automatically when follower hides.
Log: don't hide alert message automatically.
Issue: https://github.com/linuxdeepin/developer-center/issues/5622

feat: don't hide alert message automatically.

---

.obs/workflows.yml

Disable debian build cause dtkwidget may depends on qt6.6, but debian's version is 6.4.
Log: disable broken workflow build

chore: disable broken workflow build

---

src/widgets/dstyleditemdelegate.cpp

Spacing should be counts of pixel without any content between two line. for two dot, spacing = dot1 - dot2 - 1, not dot1 - dot2.
Log: fix next action rect position error
Issue: https://github.com/linuxdeepin/developer-center/issues/6379

fix: next action rect position error

---

src/widgets/dtitlebar.cpp

Move to inside the screen when exceeding the edge of the screen
Issue: https://github.com/linuxdeepin/developer-center/issues/4840

fix: Split window position error

---

src/widgets/dapplication.cpp

修复大多数按钮不响应enter事件,仅支持DApplication应用
Log: 修复大多数按钮不响应enter事件
Bug: https://pms.uniontech.com/bug-view-253935.html
Influence: 按钮响应键盘回车事件
cherry-pick form:  https://gerrit.uniontech.com/c/dtkwidget/+/239241

fix: 修复大多数按钮不响应enter事件

---

src/widgets/dprintpreviewdialog.cpp

Do not reset custom page ranges when changing printers/page size/Anything like this.
Issue: https://github.com/linuxdeepin/developer-center/issues/7983
Log: revert f53dfffb63cfcd3f005019fcc2057c652c20822b

Revert "fix: 自定义页码切换问题"

---

src/widgets/dkeysequenceedit.cpp

log: QKeyMapper::possibleKeys return QList<KeyboardModifiers> in qt 6.7

fix: support build on qt 6.7

---

src/widgets/private/dalertcontrol_p.h

Bug: https://pms.uniontech.com/bug-view-254383.html
Issue: https://github.com/linuxdeepin/developer-center/issues/8563

fix: crash when follower was destroyed

---

src/widgets/dabstractdialog.cpp

wayland下，当进程设置DGuiApplicationHelper::ColorCompositing后，DDialog需要 主动设置模糊窗口效果
Log:
Bug: https://pms.uniontech.com/bug-view-249975.html Influence: wayland下，DDialog窗口模糊

fix: 解决wayland下，DDialog窗口透明问题的问题

---

src/widgets/dmessagemanager.cpp

when compiled with Qt6, in sendMessage_helper, seems that content could be nullptr when QWebEngineView is DMainWindow's centralWidget
Log: add judgment whether content is nullptr in sendMessage_helper

fix: DMessageManager::sendMessage cause crash

---

src/widgets/daboutdialog.cpp

when compiled with Qt6, product icon size is set to windowHandle().baseSize()
which is not the same as compiled with Qt5 (fixed size 128x128)
Log: use 128x128 pixmap in DAboutDialog::setProductIcon

fix: wrong product icon size in DAboutDialog

---

src/widgets/dtitlebar.cpp

spacerItem多次设置,改为设置前先移除之前的
Log:

fix: DTitleBar动态设置Icon时间距异常

---

src/widgets/dtitlebar.cpp

DTK清除多余space使用的方法有问题,应使用itemAt而不是takeAt
Log: 控制中心标题栏返回按钮消失
Bug: https://pms.uniontech.com/bug-view-264379.html
Influence: 控制中心-标题栏

fix: 控制中心标题栏返回按钮消失

---

examples/collections/progressbarexample.cpp
examples/collections/progressbarexample.h
include/DWidget/DIndeterminateProgressbar
include/widgets/dindeterminateprogressbar.h
src/widgets/dindeterminateprogressbar.cpp
src/widgets/private/dindeterminateprogressbar_p.h

chore: 新增进度条动效和一个新进度条类

---

src/widgets/dindeterminateprogressbar.cpp
src/widgets/dsearchedit.cpp
src/widgets/private/dsearchedit_p.h

chore: 新增搜索框图标移动动画

---

src/widgets/dindeterminateprogressbar.cpp

adjust indeterminateprogressbar color
Log:

fix: adjust indeterminateprogressbar color

---

include/DWidget/DBounceAnimation
include/widgets/dbounceanimation.h
src/widgets/dbounceanimation.cpp
src/widgets/dlistview.cpp
src/widgets/private/dbounceanimation_p.h

chore: 增加滚动区域滚轮滚动到顶部或底部的回弹效果

---

include/widgets/dbuttonbox.h
src/widgets/dbuttonbox.cpp
src/widgets/dstyle.cpp
src/widgets/private/dbuttonbox_p.h

chore: 增加ButtonBox hover 和切换动画

---

include/widgets/dfloatingmessage.h
include/widgets/dmessagemanager.h
src/widgets/dfloatingmessage.cpp
src/widgets/dmessagemanager.cpp
src/widgets/dstyle.cpp
src/widgets/private/dmessagemanager_p.h

chore: 增加应用内通知动画

---

src/widgets/dtitlebar.cpp

窗口打开时没有windowstatechanged事件,不会去设置窗口状态,在showEvent中处理一下
Log:
Bug: https://pms.uniontech.com/bug-view-262201.html Influence: mainwindow最大化

fix: 如果窗口打开时即为最大化状态,则最大化图标显示错误

---

src/widgets/dmainwindow.cpp
src/widgets/dtitlebar.cpp

check environment DDE_CURRENT_COMPOSITOR is TreeLand to override
DWayland.
Log:

feat: support treeland notitlebar mode

---

include/widgets/dswitchbutton.h
src/widgets/dswitchbutton.cpp

correct the wrong initial status of switch button
Bug: https://pms.uniontech.com/bug-view-276221.html 
Log:

fix: wrong status of switch button

---

src/widgets/dlabel.cpp
src/widgets/dsimplelistview.cpp

feat: support Qt 6.8

---

src/widgets/dtitlebar.cpp

Height fixed 48
Bug: https://pms.uniontech.com/bug-view-280091.html

feat: ExpandButton in titlebar is not affected by the compact mode

---

include/widgets/dstyle.h
src/widgets/dbuttonbox.cpp
src/widgets/dfloatingmessage.cpp
src/widgets/dindeterminateprogressbar.cpp
src/widgets/dlistview.cpp
src/widgets/dmessagemanager.cpp
src/widgets/dsearchedit.cpp
src/widgets/dstyle.cpp
src/widgets/dswitchbutton.cpp

动效增加开关,通过DGuiApplication::testAttribute(DGuiApplication::HasAnimations)接口和环境变量DTK_DISABLE_ANIMATION_***控制动效总开关和单个动效开关
Log: 动效增加开关

feat: 动效增加开关

---

src/widgets/dmainwindow.cpp
src/widgets/dtitlebar.cpp

DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::IsWaylandPlatform)
https://github.com/linuxdeepin/dtkgui/pull/266

chore: use testAttribute instead of environment test

---

include/widgets/dtitlebar.h
src/widgets/dabstractdialog.cpp
src/widgets/dfloatingmessage.cpp
src/widgets/dmainwindow.cpp
src/widgets/dtitlebar.cpp

- 使用windowhandle的close()去关闭窗口
- DDialog和DMainWindow适配Treeland
pms: BUG-286173

fix: some windows have dual title bars

---

include/widgets/dplatformwindowhandle.h
src/widgets/dplatformwindowhandle.cpp

`DPlatformWindowHandle::setWindowSurfaceType(QWindow::OpenGLSurface)` needs to be called before constructing DMainWindow when use webengineview

fix: webengineView abnormal in DMainWindow

---

src/widgets/dfloatingmessage.cpp

windowHandle() is not created by default,
use close() instead.
Bug: PMS-297669

fix: resident floating message cannot be closed

---

src/widgets/dapplication.cpp

it's useful for children process. and like revert the commit
cbcb732b750a9861fd14bff91fee71927afbf995

fix: missing QT_QPA_PLATFORM for DApplication

---

src/widgets/ddrawer.cpp

窗管渲染动画问题,动画太快则会闪烁,窗管暂时无解决方案,经讨论后采用规避方案,优化动画时间和动画播放曲线
更改后在问题机L410, 还有L420自测均未再复现
Log: 修复 桌面/文管文件，打开属性窗口闪烁
Bug: https://pms.uniontech.com/bug-view-242611.html
https://pms.uniontech.com/bug-view-242571.html
Influence: DTK DDrawer控件
Change-Id: I72bb837f6a4b1393555e7a55c382d5878147a4fd

fix: 修复 桌面/文管文件，打开属性窗口闪烁

---

src/widgets/dprintpreviewwidget.cpp

it's introduced when adapting to qt6 in the commit 637e3eb.
pms:BUG-298085

fix: PrintPreview can't switch orientation

---

src/widgets/daboutdialog.cpp

There is no need to get dpr based on the window.
It causes the window can't get mouse event if using
new DAboutDialog(window)).
pms:BUG-304097

fix: titlebar can't drag after close DAboutDialog

---

src/widgets/ddrawer.cpp
src/widgets/private/ddrawer_p.h

WM's animation is confliclt with Widget.
We disable DDrawer's animation when window is invisible, and
can use D_DTK_DISABLE_ANIMATIONS to disable it's animation.
pms:BUG-242611

fix: window filickering caused by animation for DDrawer

---

src/widgets/dfontcombobox.cpp
src/widgets/dprintpreviewdialog.cpp

chore: remove warning in qt6

---

src/widgets/dprintpreviewwidget.cpp

Truncate file name to limit file's length.
pms: BUG-297841

fix: failed to save too long filename for DPrintPreviewWidget

---

src/widgets/dstyle.cpp

0x26ab code points support fewer fonts, so we added 0x25CF with a wider range of adaptability as a fallback
pms: BUG-305575

feat: increase fallback for password character

---

src/widgets/dapplication.cpp

acknowledgementLabel is wild pointer if DDialog::clearContents
is called.
aboutDialog->setLicenseEnabled is not need to call when reactive
the dialog
pms: TASK-368399

fix: accessing wild pointer for DAboutDialog

---

src/widgets/dfloatingmessage.cpp

DFloatingMessage的子控件MessageLabel支持自动换行，当文本内容包含换行符的时候，通过TextSingleLine计算的Size会与实际不符，导致整个控件宽度过大
Log:
Influence: DFloatingMessage的显示效果
Bug: https://pms.uniontech.com/bug-view-308569.html
Change-Id: I571a4c24d84cabfabaaf4a70bca8ec931347b157

fix: DFloatingMessage宽度计算

---

src/widgets/dtooltip.cpp

DToolTip的SizeHint指定了用单行计算，当DToolTip设置了自动换行，并且文本包含换行符时，会导致计算的宽度错误
Log:
Influence: DToolTip
Bug: https://pms.uniontech.com/bug-view-308569.html
Change-Id: I690a85f34b961a531444d32fe43b3a50ef38dc51

fix: DToolTip宽度计算

---

src/widgets/dstyle.cpp

原本使用的色板中button的颜色,现改为带透明度的黑色和白色
Log: 修复SwitchButton在透明窗口上显示时颜色太亮,太突兀的问题
Bug: https://pms.uniontech.com/bug-view-250757.html
Influence: DTK SwitchButton按钮 (开关)
Change-Id: Ifb231a3a9ec548d6970d240eaf2667e50ffed9f3

fix: 修复SwitchButton在透明窗口上显示时颜色太亮,太突兀的问题

---

src/widgets/private/settings/combobox.cpp

QApplication::notify has change the default action
``` qapplication.cpp
we.setAccepted(true);
we.m_spont = wheel->spontaneous() && w == receiver;
res = d->notify_helper(w, &we);
eventAccepted = we.isAccepted();
```
Event is accepted if we don't call parent class event function,
it cause event will not be passed on to it's parentWidget.
and it's different with qt5.
pms: BUG-306251

fix: wheel event is accepted in qt6

---

src/widgets/dprintpreviewdialog.cpp

incorrect format for dialog's filter.
pms: BUG-311847

fix: watermark can't select picture for PrintPreivew

---

src/widgets/dlabel.cpp

Fixed the text elision behavior in DLabel to properly handle cases
where the label contains shortcut mnemonics. The change modifies the
Qt::TextShowMnemonic flag to only be applied when the label actually has
a shortcut (d->hasShortcut). This prevents incorrect text display when
eliding labels without shortcuts.
fix: 修正带快捷键标签的文本省略行为
修复了 DLabel 中文本省略行为，正确处理包含快捷键助记符的情况。修改了
Qt::TextShowMnemonic 标志，使其仅在标签实际具有快捷键(d->hasShortcut)时
应用。这防止了在没有快捷键的标签上出现错误的文本显示。
pms: BUG-285143

fix: correct text elision behavior with shortcuts

---

.github/workflows/call-auto-release.yml
rpm/dtkwidget.spec

1. Changed version parameter to be optional in GitHub workflow to allow
more flexible release process
2. Updated rpm spec file formatting for consistency and added %{?dist}
macro for proper package naming
The changes allow for:
- More flexible release process where version can be omitted
- Better formatted spec file with proper dist macro for package naming
fix: 使发布工作流中的版本可选并更新spec文件
1. 将GitHub工作流中的版本参数改为可选，以实现更灵活的发布流程
2. 更新rpm spec文件格式以保持一致性，并添加%{?dist}宏以正确命名包
这些更改允许：
- 更灵活的发布流程，可以省略版本号
- 格式更好的spec文件，带有正确的dist宏用于包命名

fix: make version optional in release workflow and update spec file

---

src/widgets/dlistview.cpp
src/widgets/dstyleditemdelegate.cpp

- Revert "fix: prevent itemSpacing override in setBackgroundType"
- fix: prevent background type from overriding custom item spacing
pms: BUG-327525

Style error when customizing styleItem

---

src/widgets/dprintpickcolorwidget.cpp

Added supportWindowEffect() function to check for both compositing and
blur window capabilities
Updated color picker button enable state to require both composite and
blur window support
Added connection to handle hasBlurWindowChanged signal for dynamic
enable state updates
This change ensures the color picker button is only enabled when both
compositing and blur window effects are supported by the window manager,
providing better user experience by preventing the button from being
enabled in environments where the picker functionality wouldn't work
properly due to missing window effects.
Log: Color picker button now requires both compositing and blur window
support to be enabled
Influence:
1. Test color picker button enable/disable state when changing window
manager compositing settings …

feat: enhance window effect support detection
