linuxdeepin/dtkwidget

src/widgets/dapplication.cpp, src/widgets/dapplication.h
Screen scale real-time effect implemented in the Adaptation Platform theme plugin
https://github.com/linuxdeepin/qt5integration/pull/11/
=> feat: add signal "screenDevicePixelRatioChanged" for DApplication

src/widgets/dapplication.cpp, src/widgets/dapplication.h
* DApplication::customQtThemeConfigPathByUserHome
* DApplication::customQtThemeConfigPath
* DApplication::customizedQtThemeConfigPath()
=> feat: add interfaces for custom qt theme config file path

src/widgets/dblureffectwidget.cpp
修复 https://github.com/linuxdeepin/internal-discussion/issues/1332
=> fix: repaint widget mask color when the color changed

examples/dwidget-examples/collections/mainwindow.cpp, src/widgets/dabstractdialog.cpp, src/widgets/dmainwindow.cpp, src/widgets/dplatformwindowhandle.cpp, src/widgets/dplatformwindowhandle.h
修复使用no titlebar模式时，isEnableDxcb 返回值不正确
=> fix: make the dxcb to enable if the no titlebar mode is enabled

src/widgets/dblureffectwidget.cpp, src/widgets/dblureffectwidget.h, src/widgets/private/dblureffectwidget_p.h
support set blur enable
support full blur area to toplevel window
DBlurEffectWidget 支持设置是否将模糊填充到整个顶层窗口以及是否开启模糊
=> feat: add property "full" "blurEnabled" for DBlurEffectWidget

src/widgets/DBackgroundGroup, src/widgets/dbackgroundgroup.cpp, src/widgets/dbackgroundgroup.h, src/widgets/dstyleoption.cpp, src/widgets/dstyleoption.h, src/widgets/widgets.pri
Change-Id: I02a025adb21054e132bd8e50bce5c0fde9f6061f
=> feat(widgets): add dbackgroundgroup

src/widgets/DFontSizeManager, src/widgets/DPalette, src/widgets/dstyleoption.cpp, src/widgets/dstyleoption.h
DPalette: DTK style palette
DFontSizeManager: DTK standard font size level
=> feat: add DPalette and DFontSizeManager

src/widgets/dapplication.cpp, src/widgets/dthememanager.cpp, src/widgets/dthememanager.h, src/widgets/private/dapplication_p.h
theme types:
* LightType
* DarkType
=> feat: add ThemeType for DThemeManager

debian/libdtkwidget-bin.install, src/src.pro, tools/svgc/svgc.pro
fix the dtk-svgc tool install path
=> chore: remove create dtkwidgt_config.h codes

src/widgets/private/settings/content.cpp
修改标题栏的"设置"中间的多个标题的字体大小和宽度,以及间隔
Log: 修改"dsetttingdialg" 的样式, 变得更加美观
=> feat: 修改 dsettingdialg 的多级标题样式

src/widgets/dapplication.cpp
Updated English docs and added definition of APPNAME.
=> Chore: DApplication::loadTranslator documentation update

src/widgets/dprintpreviewdialog.cpp
根据A4的索引值index去设置当前默认pageSize
Log: 修改打印预览默认pageSize设置策略
Influence: 打印预览默认纸张大小
=> chore: 打印预览默认pageSize的设置策略的修改

README.md
之前的plugin未添加编译依赖，现在在README文件中说明
Log:
Influence:
=> chore: 更新README添加plugin的编译方法

CMakeLists.txt, debian/rules, doc/CMakeLists.txt, doc/src/dtkwidget-index.zh_CN.dox, doc/src/dtkwidget.zh_CN.dox, src/widgets/danchors.cpp, src/widgets/darrowbutton.cpp, src/widgets/dbackgroundgroup.cpp, src/widgets/dbaseexpand.cpp, src/widgets/dblureffectwidget.cpp, src/widgets/dbuttonbox.cpp, src/widgets/dcrumbedit.cpp, src/widgets/dfiledialog.cpp, src/widgets/dflowlayout.cpp, src/widgets/dpageindicator.cpp, src/widgets/dprintpreviewdialog.cpp, src/widgets/dsearchcombobox.cpp, src/widgets/dsearchedit.cpp, src/widgets/dsegmentedcontrol.cpp, src/widgets/dspinbox.cpp, src/widgets/dspinner.cpp, src/widgets/dstackwidget.cpp, src/widgets/dswitchlineexpand.cpp, src/widgets/dtoast.cpp, src/widgets/dwaterprogress.cpp
追加基于 doxygen 的文档构建
注：为了测试效果，这个 PR 除了提供了基本的 CMake 配置外，修改了原有文档的极个别部分来确认效果。
相关：https://github.com/linuxdeepin/dtkcore/pull/71 ， https://github.com/linuxdeepin/developer-center/discussions/3283
=> chore: build doxygen documentation

examples/dwidget-examples/collections/main.cpp
示例代码微调，去掉无效日志，头文件等
Log:
Change-Id: I2a0f0721246264d88d3e98f212722c4e1540b6fb
=> chore: 示例代码微调

src/widgets/darrowrectangle.cpp
1.传入的路径更改为outPath.united(path)；
2.使用handle方式调用模糊接口；
Log:
Influence: darrowrectangle模糊
Change-Id: If87ab051052b4288106349376acbf61d8baf7e63
=> chrone: darrowrectangle更新模糊背景调整

tests/main.cpp
Add EventLoop for ut, it's useful in some scene, for example,
when deleteLater called but we need check QPointer's value now.
Log: all ut run in event loop
Change-Id: I1f35069215d5a6beba51c1aa1dd21f51d2e582a3
=> feat: Add EventLoop for ut

.github/workflows/call-clacheck.yml, src/widgets/darrowrectangle.cpp, src/widgets/dcrumbedit.cpp, src/widgets/dlineedit.cpp, src/widgets/dtextedit.cpp
=> rebase Release/5.5 to master

debian/rules, examples/dwidget-examples/collections/main.cpp, src/widgets/dflowlayout.cpp, src/widgets/dprintpreviewdialog.cpp, src/widgets/dwaterprogress.cpp, tests/main.cpp, tests/testcases/widgets/ut_dflowlayout.cpp
=> rebase master to Release/5.5

src/widgets/darrowrectangle.cpp, src/widgets/private/darrowrectangle_p.h
set GraphicsGlowEffect in FloatWidget mode on X11
Log:
Influence: x11 DArrowRectangle::FloatWidget ui
Change-Id: I3d9dba67b3f9c23beaf47b29d15a19999200cfbc
=> fix: DArrowRectangle FloatWidget mode UI incorrect

CMakeLists.txt
- feat(cmake): to cmake
- chore: Add zh_CN readme
- fix: DListView's size calculates error
- feat(doc): add package libdtkwidget-doc
- fix: wrong option() usage in CMakeLists.txt
=> wrongoption

README.md, README.zh_CN.md, plugin/dtkuiplugin/CMakeLists.txt
update readme and CMakeList.txt
Log: dtkguiplugin
Change-Id: Ib5aa55ef9464415ee2df6acabc4867431cb9bf95
=> chore: dtkguiplugin and readme

src/CMakeLists.txt
Correct a typo in CMakeLists.txt
Log: Correct a typo in CMakeLists.txt
=> chore: correct a typo in CMakeLists.txt

README.md, README.zh_CN.md
add projects from wing-summer
Log: add more projects to readme
=> doc: add projects from wing-summer

docs/widgets/daboutdialog.zh_CN.dox, docs/widgets/index.zh_CN.md, src/widgets/daboutdialog.cpp
更新daboutdialog文档
Log:
Task: https://pms.uniontech.com/task-view-216407.html
=> docs: update daboutdialog document

.tx/deepin.conf, CMakeLists.txt, debian/changelog
=> chore: update changelog

docs/widgets/dabstractdialog.zh_CN.dox, include/dtkwidget/widgets/dabstractdialog.h, src/widgets/dabstractdialog.cpp
更新dabstractdialog文档
Log:
Task: https://pms.uniontech.com/task-view-216407.html
=> docs: update dabstractdialog docs

docs/widgets/dalertcontrol.zh_CN.dox, src/widgets/dalertcontrol.cpp
添加dalertcontrol文档
Log:
Task: https://pms.uniontech.com/task-view-216407.html
=> docs: update dalertcontrol document

docs/widgets/daboutdialog.zh_CN.dox
修复文档格式
Log:
Task: https://pms.uniontech.com/task-view-216407.html
=> fix: fix document format

.github/ISSUE_TEMPLATE/document.md
=> chore: add ISSUE_TEMPLATE

docs/widgets/darrowbutton.zh_CN.dox, src/widgets/darrowbutton.cpp
给darrowbutton添加文档注释#232
Log: add docs
Task: https://github.com/deepin-community/coding-quarter/issues/31
=> docs: add docs for widgets

docs/widgets/dimageviewer.zh_CN.dox, include/dtkwidget/widgets/dimageviewer.h, src/widgets/dimageviewer.cpp, src/widgets/private/dimageviewer_p.h, src/widgets/private/dimagevieweritems.cpp, src/widgets/private/dimagevieweritems_p.h, tests/CMakeLists.txt, tests/testcases/widgets/ut_dimageviewer.cpp
Implements the DImageViewer interface, including set image, clear, rotate, scale, gesture.
Add unit test cases and interface comment.
Log: Implements the DImageViewer interface,  including set image, clear, scale, etc.
=> feat: Implements the DImageViewer interface.

docs/widgets/ddrawer.zh_CN.dox, src/widgets/ddrawer.cpp
=> docs: update docs

docs/widgets/dimageviewer.zh_CN.dox, include/dtkwidget/widgets/dimageviewer.h, src/widgets/assets/icons/dark/icons/selection_bottomleft_40px.svg, src/widgets/assets/icons/dark/icons/selection_bottomright_40px.svg, src/widgets/assets/icons/dark/icons/selection_topleft_40px.svg, src/widgets/assets/icons/dark/icons/selection_topright_40px.svg, src/widgets/assets/icons/dtk-icon-theme.qrc, src/widgets/assets/icons/light/icons/selection_bottomleft_40px.svg, src/widgets/assets/icons/light/icons/selection_bottomright_40px.svg, src/widgets/assets/icons/light/icons/selection_topleft_40px.svg, src/widgets/assets/icons/light/icons/selection_topright_40px.svg, src/widgets/dimageviewer.cpp, src/widgets/private/dimageviewer_p.h, src/widgets/private/dimagevieweritems.cpp, src/widgets/private/dimagevieweritems_p.h, tests/testcases/widgets/ut_dimageviewer.cpp
Add DImageViewer crop image function, DGraphicsCropItem class. Add crop image unit test cases, update dox file comments.
Log: Add DImageViewer crop image function.
=> feat: Add DImageViewer crop image function.

src/widgets/dcrumbedit.cpp
Some crumbs will get out of panel frame border of DCrumbEdit when it's too long or there are too many crumbs showing in a vertical line (often happens when scrolling).
Draw border first and then draw viewport, set viewport margins.
Bug: https://pms.uniontech.com/bug-view-174437.html
Log: fix crumbs out of border
Influence: DCrumbEdit
Change-Id: I5d109fb1d01bf565f1397f92fc0eb12c7643d741
=> fix: crumbs get out of border in DCrumbEdit

src/widgets/dtitlebar.cpp
DGuiApplicationHelper::hasUserManual() will asyncCall and cached result
Log: none
Influence: manual help action
Change-Id: I7a82101bba862cbf52a033cfd2e4f7955c6238fe
=> chore: init hasManual once on showEvent

docs/CMakeLists.txt, examples/dwidget-examples/collections/CMakeLists.txt, examples/dwidget-examples/collections/imageviewerexample.cpp, examples/dwidget-examples/collections/imageviewerexample.h, examples/dwidget-examples/collections/mainwindow.cpp, src/widgets/dimageviewer.cpp, src/widgets/private/dimageviewer_p.h
Add DimageViewer example, improve crop image function.
Update dox file comment, hide internal implementation.
Log: Add DImageViewer example.
=> feat: Add DImageViewer example.

docs/widgets/dstyle.zh_CN.dox
=> docs: update docs for widget

docs/index.zh_CN.md
=> doc: add mainpage

src/widgets/dlabel.cpp, src/widgets/dstyle.cpp, src/widgets/dstyle.h, src/widgets/dstyleoption.h, src/widgets/dtooltip.cpp, src/widgets/dtooltip.h
Add ToolTip support for DListView and DLabel
Log: add ToolTip support
=> feat: add ToolTip support

include/dtkwidget/widgets/dstyle.h, include/dtkwidget/widgets/dstyleoption.h, include/dtkwidget/widgets/dtooltip.h, plugin/dtkuiplugin/CMakeLists.txt, src/widgets/dlabel.cpp, src/widgets/dstyle.cpp, src/widgets/dtooltip.cpp
Fix dtkuiplugin compile error and cherry-pick ToolTip feature from release/5.5.
=> Fix and cherry-pick new feature

docs/widgets/dsizemode.zh_CN.dox, include/dtkwidget/DWidget/DSizeMode, include/dtkwidget/util/dsizemode.h, include/dtkwidget/widgets/dapplication.h, src/widgets/dapplication.cpp, src/widgets/dmainwindow.cpp, src/widgets/dstyle.cpp, src/widgets/dtitlebar.cpp, src/widgets/private/dapplication_p.h
Send StyleChange event for all widget when
received sizemode changed.
Add SizeModeHelper for common function.
Modify radius, Shadow of MainWindow.
Log: 支持紧凑模式切换
Task: https://pms.uniontech.com/task-view-227385.html
Change-Id: I3cb83d22db1b3b058ed34443263d8321af09281d
=> feat: Add TightMode support

examples/dwidget-examples/collections/buttonexample.cpp, examples/dwidget-examples/collections/buttonexample.h, examples/dwidget-examples/collections/listviewexample.cpp, examples/dwidget-examples/collections/mainwindow.cpp, examples/dwidget-examples/collections/progressbarexample.cpp, include/dtkwidget/widgets/ddialog.h, include/dtkwidget/widgets/dfloatingmessage.h, include/dtkwidget/widgets/dpasswordedit.h, src/widgets/dbackgroundgroup.cpp, src/widgets/dcrumbedit.cpp, src/widgets/ddialog.cpp, src/widgets/dfloatingmessage.cpp, src/widgets/dkeysequenceedit.cpp, src/widgets/dpasswordedit.cpp, src/widgets/dstyle.cpp, src/widgets/dstyleditemdelegate.cpp
Modify dstyle's value when switch SizeMode;
Add compact support for dialog, listview and other base widget.
Log: 支持基本控件的紧凑模式切换
Task: https://pms.uniontech.com/task-view-227385.html
Change-Id: I8f83d1fddd723a51bd01561c3723a9c352e9d852
=> feat: Add compact support for some widgets

docs/widgets/ddialog.zh_CN.dox, src/widgets/ddialog.cpp
更新ddialog的文档 #295 
Log: update  docs
Task: deepin-community/coding-quarter#26
=> doc: update docs for ddialog

docs/CMakeLists.txt, src/widgets/dtitlebar.cpp, src/widgets/private/dsplitscreen.cpp, src/widgets/private/dsplitscreen_p.h
Adjust ui style.
Move implement from dtitlebar.cpp to splitscreen.cpp.
Log: 标题栏支持多分屏
Task: https://pms.uniontech.com/task-view-180357.html
Influence: 依赖平台插件升级，标题栏最大化按钮悬浮时分屏功能
Change-Id: I3911fd178f5ceae41a0e3f5227e4abae153583e7
=> feat: Support multi split screen for dtitlebar

src/widgets/dcombobox.cpp
ComboBox popup at the wrong position the first time after application launched. Fix this behavior.
Log: fix wrong position of ComboBox popup
Bug: https://pms.uniontech.com/bug-view-177525.html
=> fix: fix wrong position of first ComboBox popup

docs/widgets/dfeaturedisplaydialog.zh_CN.dox, examples/dwidget-examples/collections/CMakeLists.txt, examples/dwidget-examples/collections/buttonexample.cpp, examples/dwidget-examples/collections/main.cpp, examples/dwidget-examples/collections/mainwindow.cpp, examples/dwidget-examples/collections/org.deepin.dtkwiget.feature-display.json, include/dtkwidget/DWidget/DFeatureDisplayDialog, include/dtkwidget/widgets/daboutdialog.h, include/dtkwidget/widgets/dapplication.h, include/dtkwidget/widgets/dfeaturedisplaydialog.h, include/dtkwidget/widgets/dmainwindow.h, include/dtkwidget/widgets/dstyle.h, src/CMakeLists.txt, src/org.deepin.dtkwidget.feature-display.json, src/widgets/daboutdialog.cpp, src/widgets/dapplication.cpp, src/widgets/dfeaturedisplaydialog.cpp, src/widgets/diconbutton.cpp, src/widgets/dmainwindow.cpp, src/widgets/dstyle.cpp, src/widgets/dtitlebar.cpp, src/widgets/private/daboutdialog_p.h, src/widgets/private/dapplication_p.h, src/widgets/private/dfeaturedisplaydialog_p.h, src/widgets/private/dmainwindow_p.h, tests/src/widgets/ut_diconbutton.cpp, tests/testcases/widgets/ut_diconbutton.cpp
1. 增加特性对话框类接口；
2. dapplication增加特性对话框相关接口；
3. 重新布局关于对话框；
Log: 新增特性介绍功能
Task: https://pms.uniontech.com/task-view-227391.html
Influence: 特性介绍，关于介绍
Change-Id: Ie6244bd313bb385846f4c5c066108b65f5afcb4f
=> feat: 增加特性展示功能

src/translations/dtkwidget.ts, src/translations/dtkwidget_az.ts, src/translations/dtkwidget_bo.ts, src/translations/dtkwidget_ca.ts, src/translations/dtkwidget_cs.ts, src/translations/dtkwidget_de.ts, src/translations/dtkwidget_es.ts, src/translations/dtkwidget_fi.ts, src/translations/dtkwidget_fr.ts, src/translations/dtkwidget_hu.ts, src/translations/dtkwidget_it.ts, src/translations/dtkwidget_ms.ts, src/translations/dtkwidget_nl.ts, src/translations/dtkwidget_pl.ts, src/translations/dtkwidget_pt.ts, src/translations/dtkwidget_pt_BR.ts, src/translations/dtkwidget_ru.ts, src/translations/dtkwidget_sq.ts, src/translations/dtkwidget_tr.ts, src/translations/dtkwidget_ug.ts, src/translations/dtkwidget_uk.ts, src/translations/dtkwidget_zh_CN.ts, src/translations/dtkwidget_zh_HK.ts, src/translations/dtkwidget_zh_TW.ts
特性介绍需求相关文案翻译
Log: 增加特性介绍需求相关文案翻译
Task: https://pms.uniontech.com/task-view-227391.html
Influence: 特性介绍文案
Change-Id: Icd3bfeeea5ce60034bc59cf947718b24099f870a
=> feat: 特性介绍框文案翻译

docs/widgets/dfloatingbutton.zh_CN.dox, src/widgets/dfloatingbutton.cpp
更新文档
Log: docs: update the document of DFloatingButton
=> docs: update the document of DFloatingButton

docs/widgets/danchors.zh_CN.dox, src/widgets/danchors.cpp
更新danchors的文档 #306 
Task: deepin-community/coding-quarter#26
=> doc: update docs for danchors

archlinux/PKGBUILD
=> chore: remove useless dependencies

docs/widgets/dfeaturedisplaydialog.zh_CN.dox
update the interface doc of dfeaturedisplaydialog
Log: update the doc of dfeaturedisplaydialog
Influence: doc
Change-Id: I238fa7c5675bd3d51e3a7112fbe8ed549b3d3d51
=> doc: update the doc of dfeaturedisplaydialog

docs/widgets/dfilechooseredit.zh_CN.dox, src/widgets/dfilechooseredit.cpp
=> docs: update docs for dfilechooseredit

include/widgets/daboutdialog.h, src/widgets/daboutdialog.cpp, src/widgets/private/daboutdialog_p.h
1. add obsolete interfaces about acknowledgement
2. remove redundant code about acknowledgement
Log: remove redundant code about acknowledgement in daboutdialog
=> chore: Remove redundant code about acknowledgement in daboutdialog

README.md, README.zh_CN.md
=> docs: update readme

examples/collections/mainwindow.cpp
=> fix: Restore window's size for example

src/widgets/dmainwindow.cpp, src/widgets/dtitlebar.cpp
remove userless log obout sidebar
Log: remove log about sidebar
=> chore: remove log about sidebar

examples/collections/buttonexample.cpp, src/widgets/dstyle.cpp
Adjust toolbar iconsize from 24 to 16.
Log: 依赖qt5integration升级
Issue: https://github.com/linuxdeepin/dtkwidget/issues/326
=> fix: Modify size style for toolbar

CMakeLists.txt, debian/rules
=> chore: set BUILD_DOCS OFF

src/widgets/dfilechooseredit.cpp, src/widgets/dlineedit.cpp, src/widgets/dpasswordedit.cpp, src/widgets/private/dlineedit_p.h
Adjust the interval between widget to 10 for edit.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/325
=> fix: Modify edit widgets to adapt CompactMode

docs/widgets/dwindowoptionbutton.zh_CN.dox, src/widgets/dwindowoptionbutton.cpp
更新dwindowoption docs#360
Task: linuxdeepin/dtkwidget/issues/360
=> doc: update docs

src/widgets/dtitlebar.cpp
新增通过DConfig配置DTitleBar的功能
log:
Issue: https://github.com/linuxdeepin/dtkwidget/issues/367
=> feat: Add the ability to configure the default height of the DTitleBar

.tx/config
update group name
tx --version : TX Client, version=1.6.5
tx pull --all --branch master
=> chore: tx config tweak

src/widgets/daboutdialog.cpp
adjust the ui of daboutdialog
Log: adjust daboutdialog's ui
Issue: https://github.com/linuxdeepin/dtkwidget/issues/361
Influence: daboutdialog
=> fix: adjust daboutdialog's ui

docs/widgets/dwatermarkhelper.zh_CN.dox, docs/widgets/dwatermarkwidget.zh_CN.dox, include/DWidget/DWaterMarkHelper, include/util/dwidgetutil.h, include/widgets/dwatermarkhelper.h, include/widgets/dwatermarkwidget.h, src/util/dwidgetutil.cpp, src/widgets/dprintpreviewwidget.cpp, src/widgets/dwatermarkhelper.cpp, src/widgets/dwatermarkwidget.cpp
可通过DWaterMarkHelper的接口设置水印样式，并通过registerWidget添加水印
Log:
Influence: 无
Task: https://pms.uniontech.com/task-view-243575.html Change-Id: I84cf4d3fb0eb17deb0ab9c2e7b154bf884167a0b
=> feat: 增加覆盖指定界面的水印类DWaterMarkHelper

src/widgets/dstyleditemdelegate.cpp
We calculate text rect including origin text and action text
in AliginVCenter layout, and then paint it.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/408
=> fix: TextAction doesn't display in center

include/widgets/dstyle.h, src/widgets/dstyle.cpp
This reverts commit de8d8f99203863a0027b230e049b3c382b7586e3.
=> Revert "fix: icon size is abnormal when dpi > 1"

src/widgets/diconbutton.cpp
init option by virtual function baseStyleOption() in diconbutton
Log: init option by baseStyleOption() in diconbutton
=> chore: init option by baseStyleOption() in diconbutton

docs/widgets/dswitchbutton.zh_CN.dox, src/widgets/dswitchbutton.cpp
=> doc: update DSwitchButton docs

examples/collections/main.cpp, include/util/dapplicationsettings.h, src/util/dapplicationsettings.cpp
The feature has been moved to DGuiApplicationHelper in the
commit 19492cbfb71954a4939028b37ce66981d34e324e
=> feat: Deprecate DApplicationSettings

src/widgets/dapplication.cpp
remove the redundant field "version: " in about dialog
Issue: https://github.com/linuxdeepin/dtk/issues/62
=> fix: the redundant field "version" has been added

.reuse/dep5, docs/widgets/daboutdialog.zh_CN.dox, docs/widgets/dlicensedialog.zh_CN.dox, examples/collections/main.cpp, examples/collections/mainwindow.cpp, examples/collections/resources.qrc, examples/collections/resources/data/LGPLv3.txt, examples/collections/resources/data/example-license.json, include/DWidget/DLicenseDialog, include/widgets/daboutdialog.h, include/widgets/dapplication.h, include/widgets/dlicensedialog.h, src/widgets/daboutdialog.cpp, src/widgets/dapplication.cpp, src/widgets/dlicensedialog.cpp, src/widgets/private/daboutdialog_p.h, src/widgets/private/dapplication_p.h
add dlicensedialog interface and function.
Log: add license dialog widget
=> feat: add license dialog widget

examples/dwidget-examples/collections/main.cpp, examples/dwidget-examples/collections/resources.qrc, examples/dwidget-examples/collections/resources/data/GPL-2.txt, examples/dwidget-examples/collections/resources/data/MIT.txt, examples/dwidget-examples/collections/resources/data/example-license.json, src/widgets/DLicenseDialog, src/widgets/daboutdialog.cpp, src/widgets/daboutdialog.h, src/widgets/dapplication.cpp, src/widgets/dapplication.h, src/widgets/dlicensedialog.cpp, src/widgets/dlicensedialog.h, src/widgets/private/daboutdialog_p.h, src/widgets/private/dapplication_p.h, src/widgets/widgets.pri
add license feature
Log: add license feature
=> feat: add license feature

src/widgets/daboutdialog.cpp
set license label visible in aboutdialog
Log: set license label visible
=> chore: set license label visible

src/widgets/dlicensedialog.cpp, src/widgets/private/daboutdialog_p.h
connect two signals between enter action and listview on license dialog.
Log: fix the issue that it doesn't work by clicking enter action
=> fix(licensedialog): it does't work by clicking enter action

src/widgets/dlicensedialog.cpp
change the text "Credits" to "open-source software"
Log: change the text of the title on licensedialog
=> chore: change the text of the title on licensedialog

examples/collections/main.cpp, include/widgets/dapplication.h
add properties about license feature in dapplication interface.
Log: Add properties about license
=> chore: Add properties about license in dapplication interface

src/widgets/dlicensedialog.cpp
Change "open-source software" to "Open-Source Software"
Log: Change the text of the title in dlicensedialog
=> chore: Change the text of the title in dlicensedialog

src/widgets/daboutdialog.cpp, tests/main.cpp, tests/testcases/widgets/ut_daboutdialog.cpp
=> fix: fix DApplication casting error

src/widgets/dtextedit.cpp
control's palette not changed whene window activate changed
Bug: https://pms.uniontech.com/bug-view-196603.html
=> fix: TextEdit color group not update

examples/collections/buttonexample.cpp, examples/collections/dialogexample.cpp, examples/collections/editexample.cpp, examples/collections/imageviewerexample.cpp, examples/collections/layoutexample.cpp, examples/collections/lcdnumberexample.cpp, examples/collections/mainwindow.cpp, examples/collections/mainwindow.h, examples/collections/menuexample.cpp, examples/collections/pagewindowinterface.cpp, examples/collections/rubberbandexample.cpp, examples/collections/spinnerexample.cpp, examples/collections/tooltipexample.cpp, examples/collections/widgetexample.cpp, examples/collections/windowexample.cpp, plugin/dtkuidemo/mainwindow.cpp
=> feat(others): support Qt6

src/widgets/dpalettehelper.cpp
=> fix: correct copy assignment operator

tests/testcases/widgets/ut_dstyleditemdelegate.cpp
ut_dstyleditemdelegate.cpp does not using namespace Dtk::Gui; Add this to it.
Log: fix compile error of unit test
=> fix: compile error of unit test

debian/control
=> chore: remove old dependency

src/widgets/dpalettehelper.cpp, tests/testcases/widgets/ut_dsimplelistview.cpp
=> fix: compile error under qt6

src/widgets/daboutdialog.cpp, src/widgets/ddialog.cpp, src/widgets/dfontcombobox.cpp
=> fix: unit test error under qt6

src/widgets/dcombobox.cpp
改正dcombobox.cpp中一处注释
Log: Correction of a comment in Dcombobox
=> chore: A small change to dcombobox.cpp

docs/widgets/dbaseexpand.zh_CN.dox, src/widgets/dbaseexpand.cpp
=> doc: update docs for dbaseexpand

tests/CMakeLists.txt, tests/testcases/widgets/ut_daboutdialog.cpp, tests/testcases/widgets/ut_darrowlinedrawer.cpp, tests/testcases/widgets/ut_dstyleoption.cpp
Log: 移除了部分DTK6.0不支持的ut，以便通过编译，后续需要补充
=> fix: remove ut to support DTK6.0

src/widgets/dcircleprogress.cpp
=> fix DCircleProgress::valuechanged never emit

docs/widgets/dalertcontrol.zh_CN.dox, docs/widgets/dtabbar.zh_CN.dox, src/util/daccessibilitychecker.cpp, src/widgets/dmainwindow.cpp, src/widgets/dprintpreviewdialog.cpp
解决部分文档编译警告
解决cpp文件中部分注释编译警告
Issue: https://github.com/linuxdeepin/dtk/issues/96
=> chore: reduce compilation warnings

tests/CMakeLists.txt
=> fix: to fix unused qrc file in UT

tests/CMakeLists.txt, tests/data.qrc, tests/data/example-license.json, tests/testcases/widgets/ut_dlicensedialog.cpp, tests/testcases/widgets/ut_dswitchlineexpand.cpp
=> feat: add some UT

tests/test-recoverage.sh
=> fix: fix the bug of the test-recoverage.sh

include/widgets/dinputdialog_p.h
=> chore: remove useless files

tests/CMakeLists.txt, tests/testcases/widgets/ut_dcombobox.cpp
=> feat: Add UT for DComboBox

docs/widgets/dfontcombobox.zh_CN.dox, src/widgets/dfontcombobox.cpp
=> doc: update docs for dfontcombobox

tests/CMakeLists.txt, tests/testcases/widgets/ut_dpalettehelper.cpp
=> feat: add ut_dpalettehelper

src/widgets/dmainwindow.cpp, src/widgets/dtitlebar.cpp, src/widgets/private/dmainwindow_p.h
diff expand/collapse from sidebar visible
Issue: https://github.com/linuxdeepin/developer-center/issues/5297
=> fix: sidebar expand/collapse status error

tests/testcases/widgets/ut_dwatermarkhelper.cpp
=> fix: remove not working test case

src/widgets/dmainwindow.cpp, src/widgets/private/dmainwindow_p.h
setSidebarWidget will show sidebar widget
=> fix: example sidebar not show

include/widgets/dtitlebar.h, src/widgets/dtitlebar.cpp
=> chore: correct typos about action slots

src/util/dfileiconprovider.cpp, src/widgets/dprintpickcolorwidget.cpp, src/widgets/dprintpreviewdialog.cpp, src/widgets/dprintpreviewwidget.cpp, src/widgets/dsearchedit.cpp, src/widgets/dstyle.cpp, src/widgets/dwaterprogress.cpp, src/widgets/private/dimagevieweritems.cpp, src/widgets/private/dtitlebareditpanel.cpp
Replacing QIcon::fromTheme.
Issue: linuxdeepin/developer-center#4112
=> feat: use DIconTheme::findQIcon

docs/widgets/denhancedwidget.zh_CN.dox, src/widgets/denhancedwidget.cpp
更新denhancedwidget的文档,添加示例代码及图片
=> doc: update docs for denhancedwidget

include/DWidget/DDesktopServices, include/util/ddesktopservices.h, src/util/ddesktopservices_linux.cpp
move ddesktopservices from dtkwidget to dtkgui
Issue: linuxdeepin/dtk#134
=> feat: move ddesktopservices to dtkgui

src/widgets/dstyleditemdelegate.cpp, src/widgets/dtextedit.cpp
-  fix logical judgment errors 
-  nullptr check
=>  nullptr check &&  logical judgment errors 

src/widgets/dstyle.cpp
Frequent construction and destruction will connect / disconnect dbus...
=> fix: dconfig frequent construction and destruction

src/widgets/daboutdialog.cpp, src/widgets/dmainwindow.cpp, src/widgets/dtitlebar.cpp, tests/testcases/widgets/ut_dimageviewer.cpp
replace the obsolete interface
Log: Adapt to Qt6.6.1
=> Adapt to Qt6.6.1

src/widgets/dlineedit.cpp, src/widgets/dpasswordedit.cpp, src/widgets/dstyle.cpp, src/widgets/private/dlineedit_p.h
1. revert the commit (https://github.com/linuxdeepin/dtkwidget/pull/553)
2.  modify the password character
=> Black circle in PasswordLineEdit

include/widgets/dlistview.h, src/widgets/dlistview.cpp
as title
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7673
=> fix: fix the problem of text position in dstyleditemdelegate

.reuse/dep5
reuse ignore *.ts
Log: reuse ignore *.ts
=> chore: reuse ignore *.ts

src/widgets/ddialog.cpp
Set the space for title layout to 0
Issue: https://github.com/linuxdeepin/developer-center/issues/8418
=> feat: modify the spacing between the title and the top

src/widgets/dsimplelistview.cpp
Conditional compilation package incomplete
Log:
=> fix: Compile issues

src/widgets/dslider.cpp
调整滑动条横条和刻度颜色
Log: 调整滑动条横条和刻度颜色
Bug: https://pms.uniontech.com/bug-view-254295.html
Influence: 调整滑动条横条和刻度颜色
=> fix: 调整滑动条横条和刻度颜色

src/widgets/dtitlebar.cpp
=> fix: access wild pointer for targetWindowHandle

.reuse/dep5
=> chore: reuse warning

.tx/config
1. Removed minimum_perc and mode settings from main section
2. Updated resource identifier from 'dwidget' to hash-based identifier
3. Cleaned up whitespace in the configuration file
The changes were made to align with Transifex's updated configuration
requirements and to standardize resource identifiers across the project.
The hash-based identifier provides better uniqueness and consistency.
Influence:
1. Verify translations are still being properly synced with Transifex
2. Check that translation files are being generated correctly
3. Ensure no regression in translation functionality
fix: 更新Transifex配置
1. 从main部分移除了minimum_perc和mode设置
2. 将资源标识符从'dwidget'更新为基于哈希的标识符
3. 清理了配置文件中的空白字符
这些更改是为了符合Transifex更新的配置要求，并使项目中的资源标识符标准
化。基于哈希的标识符提供了更好的唯一性和一致性。
Influence:
1. 验证翻译仍能正确与Transifex同步
2. …
=> fix: update transifex configuration
